### ISSUE TITLE
Validation of properly formed name and partition strings

### ISSUE THREAD

**Issue by swormke** [F5Networks/f5-icontrol-rest-python#44]
There are rules in BIGIP for what characters the names and partitions can have as well as length limits etc.  We need to beef up the validation of the strings users are calling the verbs with the account for these.

For example names can't start with digits.

**Comment by msaundrs** [comment]
If a VIP/Pool is created with an iApp, the path is longer than when created with the GUI, and contains an extra  '~' char. This appears to be in conflict with the error checking done in the _validate_name_partition_subpath(element): function of session.py.
Perhaps I went about coding this the wrong way, but here is example code that will demonstrate the issue.
If looking for a pool created thru the GUI, it runs fine.
If looking for a pool created thru iApp, it fails until the error checking in session.py is commented out. (Due to the extra '~' in the iApp path)
[Issue_with_error_checking_in__validate_name_partition_subpth_function_example.txt]
(https://github.com/F5Networks/f5-icontrol-rest-python/files/2563478/Issue_with_error_checking_in__validate_name_partition_subpth_function_example.txt)

**Comment by msaundrs** [comment]
There appears to be an issue with the validation in the _validate_name_partition_subpath function in session.py.
When a new VIP/Pool is created with an iApp, the path is longer than when these are created via the GUI, and the path contains an extra tilde.
It is this extra tilde that is getting caught up in the error check of the function.
I have attached sample code that will demonstrate the issue.
Run the code specifying a pool created thru the GUI, and it runs fine.
Run the code specifying a pool created via an iApp, and it fails until the tilde checking is removed from the above function.
GUI pool path:
```/~Common~test_app.domain.com_pool```
iApp pool path:
```/~Common~test_app.domain.com.app~test_app.domain.com_pool```
[Issue_with_error_checking_in__validate_name_partition_subpth_function_example.txt](https://github.com/F5Networks/f5-icontrol-rest-python/files/2563556/Issue_with_error_checking_in__validate_name_partition_subpth_function_example.txt)

**Comment by f5-rahm** [comment]
archiving this repo, this request will not be implemented.
